"""Container entrypoint for the OpenManus Platform.

OpenManus reads its LLM settings from ``config/config.toml``. That file is
git-ignored and must never be baked into an image, so this entrypoint creates it
at container start, then ``exec``s the real command (``python run_platform.py``
by default).

Configuration sources, in order of precedence:

1. A complete TOML file at ``$OPENMANUS_CONFIG_FILE`` (default
   ``/etc/secrets/config.toml`` — where Render mounts "Secret Files").
   Use this when you need sections beyond ``[llm]`` (proxies, MCP, sandbox...).
2. ``LLM_*`` environment variables (the common case):

       LLM_MODEL             required   e.g. claude-sonnet-4-5, gpt-4.1
       LLM_BASE_URL          required   e.g. https://api.anthropic.com/v1/
       LLM_API_KEY           required (first/default key)
       LLM_API_KEYS          optional comma- or newline-separated local failover keys
       LLM_API_TYPE          optional   "" | azure | aws | ollama | jiekou
       LLM_API_VERSION       optional   Azure only
       LLM_MAX_TOKENS        optional   default 8192
       LLM_MAX_INPUT_TOKENS  optional   default unlimited
       LLM_TEMPERATURE       optional   default 0.0
       LLM_VISION_MODEL      optional   adds an [llm.vision] section
       LLM_VISION_BASE_URL   optional   defaults to LLM_BASE_URL
       LLM_VISION_API_KEY    optional   defaults to LLM_API_KEY

3. An existing ``config/config.toml`` (e.g. bind-mounted) is left untouched.

If none of these are present the server still starts — the UI and API work —
but agent tasks will fail until an LLM is configured.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT / "config"
CONFIG_FILE = CONFIG_DIR / "config.toml"
DEFAULT_SECRET_FILE = "/etc/secrets/config.toml"
DEFAULT_COMMAND = [sys.executable, "run_platform.py"]


def log(message: str) -> None:
    print(f"[entrypoint] {message}", flush=True)


def env(name: str) -> str | None:
    value = os.environ.get(name)
    return value.strip() if value and value.strip() else None


def toml_str(value: str) -> str:
    # JSON string escaping is a valid TOML basic string for all practical inputs.
    return json.dumps(value)


def toml_num(name: str, raw: str, kind: type) -> str:
    try:
        return repr(kind(raw))
    except ValueError:
        sys.exit(f"[entrypoint] {name} must be a{'n integer' if kind is int else ' number'}, got {raw!r}")


def render_llm_config() -> str:
    model, base_url, api_key = env("LLM_MODEL"), env("LLM_BASE_URL"), env("LLM_API_KEY")
    missing = [n for n, v in (("LLM_MODEL", model), ("LLM_BASE_URL", base_url), ("LLM_API_KEY", api_key)) if not v]
    if missing:
        sys.exit(
            f"[entrypoint] LLM_API_KEY is set but {', '.join(missing)} "
            "is missing. Set all of LLM_MODEL, LLM_BASE_URL and LLM_API_KEY."
        )

    lines = [
        "# Generated by deploy/entrypoint.py from environment variables at container start.",
        "# Do not edit by hand; changes are overwritten on the next restart.",
        "[llm]",
        f"model = {toml_str(model)}",
        f"base_url = {toml_str(base_url)}",
        f"api_key = {toml_str(api_key)}",
        f"max_tokens = {toml_num('LLM_MAX_TOKENS', env('LLM_MAX_TOKENS') or '8192', int)}",
        f"temperature = {toml_num('LLM_TEMPERATURE', env('LLM_TEMPERATURE') or '0.0', float)}",
    ]
    raw_keys = os.environ.get("LLM_API_KEYS", "")
    api_keys = [item.strip() for item in raw_keys.replace("\n", ",").split(",") if item.strip()]
    if api_keys:
        lines.append(f"api_keys = {json.dumps(api_keys)}")
    if env("LLM_MAX_INPUT_TOKENS"):
        lines.append(f"max_input_tokens = {toml_num('LLM_MAX_INPUT_TOKENS', env('LLM_MAX_INPUT_TOKENS'), int)}")
    if env("LLM_API_TYPE"):
        lines.append(f"api_type = {toml_str(env('LLM_API_TYPE'))}")
    if env("LLM_API_VERSION"):
        lines.append(f"api_version = {toml_str(env('LLM_API_VERSION'))}")

    if env("LLM_VISION_MODEL"):
        lines += [
            "",
            "[llm.vision]",
            f"model = {toml_str(env('LLM_VISION_MODEL'))}",
            f"base_url = {toml_str(env('LLM_VISION_BASE_URL') or base_url)}",
            f"api_key = {toml_str(env('LLM_VISION_API_KEY') or api_key)}",
            f"max_tokens = {toml_num('LLM_MAX_TOKENS', env('LLM_MAX_TOKENS') or '8192', int)}",
            f"temperature = {toml_num('LLM_TEMPERATURE', env('LLM_TEMPERATURE') or '0.0', float)}",
        ]
        if env("LLM_API_TYPE"):
            lines.append(f"api_type = {toml_str(env('LLM_API_TYPE'))}")
        if env("LLM_API_VERSION"):
            lines.append(f"api_version = {toml_str(env('LLM_API_VERSION'))}")

    return "\n".join(lines) + "\n"


def write_private(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    os.chmod(path, 0o600)


def prepare_config() -> None:
    secret_file = Path(env("OPENMANUS_CONFIG_FILE") or DEFAULT_SECRET_FILE)
    if secret_file.is_file():
        shutil.copyfile(secret_file, CONFIG_FILE)
        os.chmod(CONFIG_FILE, 0o600)
        log(f"Using LLM configuration from {secret_file}")
        return

    if env("LLM_API_KEY"):
        write_private(CONFIG_FILE, render_llm_config())
        log(
            "Generated config/config.toml from LLM_* environment variables "
            f"(model={env('LLM_MODEL')}, base_url={env('LLM_BASE_URL')})"
        )
        return

    if CONFIG_FILE.is_file():
        log("Using existing config/config.toml")
        return

    log(
        "WARNING: no LLM configuration found. The UI and API will start, but agent "
        "tasks will fail until you set LLM_MODEL, LLM_BASE_URL and LLM_API_KEY "
        f"(or provide {DEFAULT_SECRET_FILE})."
    )


def main() -> None:
    os.chdir(ROOT)
    prepare_config()
    command = sys.argv[1:] or DEFAULT_COMMAND
    log(f"Starting: {' '.join(command)}")
    os.execvp(command[0], command)


if __name__ == "__main__":
    main()
