"""Container entrypoint for the OpenManus Platform.

OpenManus reads its LLM settings from ``config/config.toml``. That file is
git-ignored and must never be baked into an image, so this entrypoint creates it
at container start, then ``exec``s the real command (``python run_platform.py``
by default).

Configuration sources, in order of precedence:

1. A complete TOML file at ``$OPENMANUS_CONFIG_FILE`` (default
   ``/etc/secrets/config.toml`` — where Render mounts "Secret Files").
   Use this when you need sections beyond ``[llm]`` (proxies, MCP, sandbox...).
2. ``LLM_*`` environment variables (the common case):

       LLM_MODEL             required   e.g. claude-sonnet-4-5, gpt-4.1
       LLM_BASE_URL          required   e.g. https://api.anthropic.com/v1/
       LLM_API_KEY           required (first/default key)
       LLM_API_KEYS          optional comma- or newline-separated local failover keys
       LLM_API_TYPE          optional   "" | azure | aws | ollama | jiekou
       LLM_API_VERSION       optional   Azure only
       LLM_MAX_TOKENS        optional   default 8192
       LLM_MAX_INPUT_TOKENS  optional   default unlimited
       LLM_TEMPERATURE       optional   default 0.0
       LLM_VISION_MODEL      optional   adds an [llm.vision] section
       LLM_VISION_BASE_URL   optional   defaults to LLM_BASE_URL
       LLM_VISION_API_KEY    optional   defaults to LLM_API_KEY

3. An existing ``config/config.toml`` (e.g. bind-mounted) is left untouched.

If none of these are present the server still starts — the UI and API work —
but agent tasks will fail until an LLM is configured.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT / "config"
CONFIG_FILE = CONFIG_DIR / "config.toml"
DEFAULT_SECRET_FILE = "/etc/secrets/config.toml"
DEFAULT_COMMAND = [sys.executable, "run_platform.py"]


def log(message: str) -> None:
    print(f"[entrypoint] {message}", flush=True)


def env(name: str) -> str | None:
    value = os.environ.get(name)
    return value.strip() if value and value.strip() else None


def toml_str(value: str) -> str:
    # JSON string escaping is a valid TOML basic string for all practical inputs.
    return json.dumps(value)


def toml_num(name: str, raw: str, kind: type) -> str:
    try:
        return repr(kind(raw))
    except ValueError:
        sys.exit(f"[entrypoint] {name} must be a{'n integer' if kind is int else ' number'}, got {raw!r}")


def key_pool(name: str) -> list[str]:
    values: list[str] = []
    raw = os.environ.get(name, "")
    values.extend(item.strip() for item in raw.replace("\n", ",").split(",") if item.strip())

    # Docker .env files are clearer and safer when each secret occupies its own
    # line. Support both ..._API_KEY_01 and the older ..._API_KEYS_01 spelling.
    numbered_prefixes = [name]
    if name.endswith("_API_KEYS"):
        numbered_prefixes.append(name[:-1])
    numbered: list[tuple[int, str, str]] = []
    for variable, value in os.environ.items():
        for prefix in numbered_prefixes:
            match = re.fullmatch(re.escape(prefix) + r"_(\d+)", variable)
            if match and value.strip():
                numbered.append((int(match.group(1)), variable, value.strip()))
                break
    values.extend(value for _, _, value in sorted(numbered))
    return list(dict.fromkeys(values))


def append_pool(lines: list[str], section: str, model: str | None, base_url: str | None, keys: list[str], max_tokens: str, temperature: str) -> None:
    if not (model and base_url and keys):
        return
    lines += [
        "",
        f"[llm.{section}]",
        f"model = {toml_str(model)}",
        f"base_url = {toml_str(base_url)}",
        f"api_key = {toml_str(keys[0])}",
        f"api_keys = {json.dumps(keys)}",
        'api_type = "openai"',
        f"max_tokens = {max_tokens}",
        f"temperature = {temperature}",
    ]


def render_llm_config() -> str:
    # When LOCAL_LLM_* is configured, it becomes the default provider. The
    # existing LLM_* values remain the backward-compatible cloud-only mode.
    local_model = env("LOCAL_LLM_MODEL")
    local_base = env("LOCAL_LLM_BASE_URL")
    local_key = env("LOCAL_LLM_API_KEY") or "ollama"
    model = local_model or env("LLM_MODEL")
    base_url = local_base or env("LLM_BASE_URL")
    api_key = local_key if local_model else env("LLM_API_KEY")
    missing = [("LOCAL_LLM_MODEL" if local_model else "LLM_MODEL", model), ("LOCAL_LLM_BASE_URL" if local_model else "LLM_BASE_URL", base_url), ("LOCAL_LLM_API_KEY" if local_model else "LLM_API_KEY", api_key)]
    missing = [n for n, v in missing if not v]
    if missing:
        sys.exit(f"[entrypoint] Missing {', '.join(missing)}. Configure the local provider or LLM_MODEL, LLM_BASE_URL and LLM_API_KEY.")

    lines = [
        "# Generated by deploy/entrypoint.py from environment variables at container start.",
        "# Do not edit by hand; changes are overwritten on the next restart.",
        "[llm]",
        f"model = {toml_str(model)}",
        f"base_url = {toml_str(base_url)}",
        f"api_key = {toml_str(api_key)}",
        f"max_tokens = {toml_num('LLM_MAX_TOKENS', env('LLM_MAX_TOKENS') or '8192', int)}",
        f"temperature = {toml_num('LLM_TEMPERATURE', env('LLM_TEMPERATURE') or '0.0', float)}",
    ]
    api_keys = key_pool("LOCAL_LLM_API_KEYS") or key_pool("LLM_API_KEYS")
    if api_keys and not local_model:
        lines.append(f"api_keys = {json.dumps(api_keys)}")

    max_tokens = toml_num("LLM_MAX_TOKENS", env("LLM_MAX_TOKENS") or "8192", int)
    temperature = toml_num("LLM_TEMPERATURE", env("LLM_TEMPERATURE") or "1.0", float)
    append_pool(lines, "vision", env("VISION_LLM_MODEL"), env("VISION_LLM_BASE_URL"), key_pool("VISION_LLM_API_KEYS"), max_tokens, temperature)
    append_pool(lines, "heavy_coding", env("HEAVY_CODING_LLM_MODEL"), env("HEAVY_CODING_LLM_BASE_URL"), key_pool("HEAVY_CODING_LLM_API_KEYS"), max_tokens, temperature)
    append_pool(lines, "fallback", env("OLLAMA_FALLBACK_LLM_MODEL"), env("OLLAMA_FALLBACK_LLM_BASE_URL"), key_pool("OLLAMA_FALLBACK_LLM_API_KEYS"), max_tokens, temperature)

    # Backward-compatible migration path for existing local-first deployments.
    legacy_model = env("CLOUD_LLM_MODEL") or (env("LLM_MODEL") if local_model else None)
    legacy_base = env("CLOUD_LLM_BASE_URL") or (env("LLM_BASE_URL") if local_model else None)
    legacy_keys = key_pool("CLOUD_LLM_API_KEYS") or ([env("CLOUD_LLM_API_KEY")] if env("CLOUD_LLM_API_KEY") else [])
    if not key_pool("OLLAMA_FALLBACK_LLM_API_KEYS"):
        append_pool(lines, "fallback", legacy_model, legacy_base, legacy_keys, max_tokens, temperature)
    if env("LLM_MAX_INPUT_TOKENS"):
        lines.append(f"max_input_tokens = {toml_num('LLM_MAX_INPUT_TOKENS', env('LLM_MAX_INPUT_TOKENS'), int)}")
    if env("LLM_API_TYPE"):
        lines.append(f"api_type = {toml_str(env('LLM_API_TYPE'))}")
    if env("LLM_API_VERSION"):
        lines.append(f"api_version = {toml_str(env('LLM_API_VERSION'))}")

    if env("LLM_VISION_MODEL"):
        lines += [
            "",
            "[llm.vision]",
            f"model = {toml_str(env('LLM_VISION_MODEL'))}",
            f"base_url = {toml_str(env('LLM_VISION_BASE_URL') or base_url)}",
            f"api_key = {toml_str(env('LLM_VISION_API_KEY') or api_key)}",
            f"max_tokens = {toml_num('LLM_MAX_TOKENS', env('LLM_MAX_TOKENS') or '8192', int)}",
            f"temperature = {toml_num('LLM_TEMPERATURE', env('LLM_TEMPERATURE') or '0.0', float)}",
        ]
        if env("LLM_API_TYPE"):
            lines.append(f"api_type = {toml_str(env('LLM_API_TYPE'))}")
        if env("LLM_API_VERSION"):
            lines.append(f"api_version = {toml_str(env('LLM_API_VERSION'))}")

    return "\n".join(lines) + "\n"


def write_private(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    os.chmod(path, 0o600)


def prepare_config() -> None:
    secret_file = Path(env("OPENMANUS_CONFIG_FILE") or DEFAULT_SECRET_FILE)
    if secret_file.is_file():
        shutil.copyfile(secret_file, CONFIG_FILE)
        os.chmod(CONFIG_FILE, 0o600)
        log(f"Using LLM configuration from {secret_file}")
        return

    if env("LOCAL_LLM_MODEL") or env("LLM_API_KEY"):
        write_private(CONFIG_FILE, render_llm_config())
        log(
            "Generated config/config.toml from LLM_* environment variables "
            f"(model={env('LLM_MODEL')}, base_url={env('LLM_BASE_URL')})"
        )
        return

    if CONFIG_FILE.is_file():
        log("Using existing config/config.toml")
        return

    log(
        "WARNING: no LLM configuration found. The UI and API will start, but agent "
        "tasks will fail until you set LLM_MODEL, LLM_BASE_URL and LLM_API_KEY "
        f"(or provide {DEFAULT_SECRET_FILE})."
    )


def main() -> None:
    os.chdir(ROOT)
    prepare_config()
    command = sys.argv[1:] or DEFAULT_COMMAND
    log(f"Starting: {' '.join(command)}")
    os.execvp(command[0], command)


if __name__ == "__main__":
    main()
